export const SET_LOADING = 'SET_LOADING';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_WOMENPRODUCTS = 'GET_WOMENPRODUCTS';
export const GET_WOMANPRODUCT = 'GET_WOMENPRODUCT';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';
